language: node_js
node_js:
  - "8"
  - "10"
  - "13"
cache:
  directories:
    - node_modules
env:
  global:
    - CC_TEST_REPORTER_ID=c7ef634d96a67d1c98a87dadc02205dc01f9b935cd10699d9d1bce46ccdcbd27
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
install:
  - npm install
  - npm install -g jest
script:
  - npm test
